# Default values for cb-ci-casc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operationCenter:
  # -- http or https
  protocol: "https"
  # -- DNS zone (Eg: Route 53 in Hosted Zone in AWS)
  hostname: "example.com"
  # -- Subdomain prefix used for all CloudBees CI applications (Operation Center and Controllers)
  subdomain: "ci"
  ingress:
    # -- alb or nlb
    class: alb
  casc:
    # -- Location of CloudBees Bundle Storage for Controller
    controllerBundleStorageSCM: "https://github.com/carlosrodlop/cb-casc-controllers.git"
  credentials:
    # -- Github Secret pair
    github:
      # -- Github Secret for token
      token: "ghp_xxxxExampleToken"
      # -- Github Secret for user
      user: "gh_ExampleUser"
controllers:
  # -- Enable Limit Range and Resource Quoatas
  policies: true
  loadTest:
    # -- Number of Load Controllers for Performance Testing
    controllers: 3
    # -- Deployment of stress pods in the agent namespace using kubeStresscheckPod
    namespace:
      # -- Activation flag
      enable: false
      # -- Number of replicas
      replicas: 2
agents:
  # -- Agents Namespace name
  namespace: "cbci-agents"
  # -- Enable Limit Range and Resource Quoatas
  policies: true
  loadTest:
    # -- Deployment of stress pods in the agent namespace using kubeStresscheckPod
    namespace:
      # -- Activation flag
      enable: false
      # -- Number of replicas
      replicas: 2
