# Default values for cb-ci-casc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  dashboard:
    # -- Configmap for defining CloudBees CI Controllers
    cbci-controllers-configmap: false
