# Default values for cb-ci-casc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

OperationCenter:
  Protocol: "https"
  Hostname: "ci.example.com"
  Casc:
    OperationCenterBundle: "modern"
    ControllerBundleStorageSCM: "https://github.com/carlosrodlop/cb-casc-controllers.git"
  Credentials:
    Github:
      Token: "ghp_xxxxxxxxxxxxxxxxxxxxExampleToken"
      User: "gh_ExampleUser"
ManagedControllers:
  loadCount: 5
Agents:
  Namespace: "cbci-agents"
