#Common_Configuration
  CasC:
    Enabled: true
  ConfigMapName: oc-casc-bundle
  ContainerEnv:
    - name: SECRETS
      value: /var/run/secrets/cjoc
  ExtraVolumes:
    - name: oc-secrets
      secret:
        secretName: oc-secrets
    # - name: mc-load-casc-bundle
    #   configMap:
    #     name: mc-load-casc-bundle  
  ExtraVolumeMounts:
    - name: oc-secrets
      mountPath: /var/run/secrets/cjoc
      readOnly: true
    # - name: mc-load-casc-bundle
    #   mountPath: /var/jenkins_home/cb-casc-bundles-store/modern.load-boy.items
    #   readOnly: true
  License:
    Evaluation:
      Enabled: true
      FirstName: ${LicFirstName}
      LastName: ${LicLastName}
      Email: ${LicEmail}
      Company: ${LicCompany}
Agents:
  SeparateNamespace:
    Enabled: true
    Name: cbci-agents

