OperationCenter:
  Protocol: ${protocol}
  Hostname: ${hostname}
  Ingress:
    Class: ${ingressClass}
  Casc:
    ControllerBundleStorageSCM: ${c_casc_repo}
  Credentials:
    Github:
      Token: ${secretGHToken}
      User: ${secretGHUser}
LoadControllers:
  ControllersNumber: ${LoadControllers}
  JobsPerController: ${JobsPerController}
  JobFrequency: ${JobFrequency}
Agents:
  Namespace: ${agentNamespace}
