# Default values for cb-ci-casc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

OperationCenter:
  Protocol: "https"
  Hostname: "example.com"
  Subdomain: "ci"
  Ingress:
    Class: alb
  Casc:
    OperationCenterBundle: "modern"
    ControllerBundleStorageSCM: "https://github.com/carlosrodlop/cb-casc-controllers.git"
  Credentials:
    Github:
      Token: "ghp_xxxxxxxxxxxxxxxxxxxxExampleToken"
      User: "gh_ExampleUser"
LoadControllers:
  ControllersNumber: 5
  JobsPerController: 2
  JobFrequency: 30
Agents:
  Namespace: "cbci-agents"
