---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.agents.namespace | quote }}
  labels:
    name: {{ .Values.agents.namespace | quote }}
---
{{- if or (.Values.agents.cache.enable) (eq (.Values.agents.cache.enable | toString) "<nil>") }}
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "maven-cache"
  namespace: {{ .Values.agents.namespace | quote }}
spec:
  storageClassName: {{ .Values.agents.cache.storageClassName | quote | default "gp3" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
{{- end }}
