---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.agents.namespace | quote }}
  labels:
    name: {{ .Values.agents.namespace | quote }}
---
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "maven-cache"
  namespace: {{ .Values.agents.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
