apiVersion: v1
kind: Secret
metadata:
  name: oc-secrets
  annotations:
    docs: "https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc"
type: Opaque
data:
  githubToken: {{ .Values.operationCenter.credentials.github.token | b64enc | quote}}
  githubUser: {{ .Values.operationCenter.credentials.github.user | b64enc | quote }}
  jenkinsPass: {{ .Values.operationCenter.credentials.jenkins.pass | b64enc | quote }}
