apiVersion: v1
kind: ResourceQuota
metadata:
    name: "r.quota-cb.apps"
spec:
    hard:
        # 3 reserved apps: 1 cjoc + 2 spare controllers
        {{- $num_ci_apps := add .Values.controllers.loadControllersNumber 3 }}
        {{- with .Values.controllers.loadControllersNumber }}
        pods: {{ $num_ci_apps }}
        #Max 4units per Controller
        cpu: {{ mul $num_ci_apps 4 }}
        #Max 16GB per Controller
        memory: {{ mul $num_ci_apps 16 }}Gi
        {{- end }}
