apiVersion: v1
kind: ResourceQuota
metadata:
    name: "r.quota-cb.agents"
    namespace: {{ .Values.agents.namespace | quote }}
spec:
    hard:
        # 3 reserved apps: 1 cjoc + 2 spare controllers
        {{- $num_ci_apps := add .Values.controllers.loadControllersNumber 3 -}}
        # Every controller should not have attached more than 25 pods running simultaneously
        {{- $num_ci_agents := mul $num_ci_apps 25 -}}
        pods: {{ $num_ci_agents }}
        # Max 2Gi per Agents, not all agents requires de same memory
        limits.memory: "{{ mul $num_ci_agents 2 }}Gi"
