apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "maven-cache"
  namespace: "{{ .Values.Agents.Namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
