{{- if or (.Values.grafana.dashboard.cbciControllersConfigmap) (eq (.Values.grafana.dashboard.cbciControllersConfigmap | toString) "<nil>") }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: grafana-cb-controllers
  annotations:
    k8s-sidecar-target-directory: /var/lib/grafana/dashboards/grafana-dashboards-cloudbees
data:
  grafana-cb-controllers.json: |-
{{ .Files.Get "dashboards/cloudbees-controllers.json" | indent 4 }}
{{- end }}
