apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-controllers-cbci
  labels:
    app: service-monitor-controllers-cbci
spec:
  namespaceSelector:
    matchNames:
      - cbci
  selector:
    matchLabels:
      com.cloudbees.cje.type: master
  endpoints:
    - port: http
      interval: 30s
      path: /prometheus/
