apiVersion: v1
kind: Secret
metadata:
  name: oc-secrets
  annotations:
    docs: "https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc"
type: Opaque
data:
  githubToken: "{{ .Values.OperationCenter.Credentials.Github.Token | b64enc }}"
  githubUser: "{{ .Values.OperationCenter.Credentials.Github.User | b64enc }}"
  jenkinsPass: "{{ .Values.OperationCenter.Security.JenkinsPass | b64enc }}"
