OperationsCenter:
  # OperationsCenter.Enabled -- Disable for particular use case like setting up namespaces to host masters only
  Enabled: true
  # Operations Center container image
  image:
    # OperationsCenter.image.registry -- Docker registry for Operations Center
    registry: '62049'
    # OperationsCenter.image.repository -- Docker image repository for Operations Center
    repository: 'cloudbees-oc'
    # OperationsCenter.image.tag -- Docker image tag for Operations Center
    tag: latest
    # OperationsCenter.image.pullPolicy -- https://kubernetes.io/docs/concepts/containers/images/#updating-images
    pullPolicy: null
  JavaOpts: >-
    -XX:InitialRAMPercentage=50.0
    -XX:MaxRAMPercentage=50.0
  Resources:
    Limits:
      Memory: "4G"
      Cpu: 2
    Requests:
      Memory: "4G"
      Cpu: 2
  CasC:
    Enabled: true
  ConfigMapName: oc-casc-bundle
  ContainerEnv:
    - name: SECRETS
      value: /var/run/secrets/cjoc
  ExtraVolumes:
    - name: oc-secrets
      secret:
        secretName: oc-secrets
  ExtraVolumeMounts:
    - name: oc-secrets
      mountPath: /var/run/secrets/cjoc
      readOnly: true
  NodeSelector:
    ci_type: cb-apps
  Tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule
      #  License:
      #Evaluation:
      #Enabled: true
      #FirstName: ${LicFirstName}
      #LastName: ${LicLastName}
      #Email: ${LicEmail}
      #Company: ${LicCompany}
Hibernation:
  Enabled: true
Master:
  JavaOpts: >-
    -XX:InitialRAMPercentage=50.0
    -XX:MaxRAMPercentage=50.0
Agents:
  SeparateNamespace:
    Enabled: true
    Name: ${agentNamespace}
# Common parameters for all components. These can be overridden in each component.
#Common:
#  image:
#    # Common.image.registry -- container registry for the images
#    registry: '62049'
#    # Common.image.tag -- container image tag
#    tag: '2.401.3.3'
#    # Common.image.pullPolicy -- Used to override the default pull policy for all images
#    pullPolicy: null
