OperationsCenter:
  #Common_Configuration
  Annotations:
    # vault.hashicorp.com/agent-inject: 'true'
    # vault.hashicorp.com/role: 'jenkins'
    # vault.hashicorp.com/template-static-secret-render-interval: "1m"
    # vault.hashicorp.com/agent-inject-secret-casc-config.txt: 'jenkins/data/casc/config'
    # vault.hashicorp.com/agent-inject-default-template: 'json'
    # vault.hashicorp.com/agent-limits-ephemeral: '1Gi'
  CasC:
    Enabled: true
  ConfigMapName: oc-casc-bundle
  ContainerEnv:
    - name: SECRETS
      value: /var/run/secrets/cjoc
  ExtraVolumes:
    - name: oc-secrets
      secret:
        secretName: oc-secrets
    # - name: mc-load-casc-bundle
    #   configMap:
    #     name: mc-load-casc-bundle
  ExtraVolumeMounts:
    - name: oc-secrets
      mountPath: /var/run/secrets/cjoc
      readOnly: true
    # - name: mc-load-casc-bundle
    #   mountPath: /var/jenkins_home/cb-casc-bundles-store/modern.load-boy.items
    #   readOnly: true
  NodeSelector:
    ci_type: cb-apps
  Tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule
  License:
    Evaluation:
      Enabled: true
      FirstName: ${LicFirstName}
      LastName: ${LicLastName}
      Email: ${LicEmail}
      Company: ${LicCompany}
Hibernation:
  Enabled: true
Agents:
  SeparateNamespace:
    Enabled: true
    Name: cbci-agents
