OperationsCenter:
  #Common_Configuration
  NodeSelector:
    ci_type: cb-apps
  Tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule
  License:
    Evaluation:
      Enabled: true
      FirstName: ${LicFirstName}
      LastName: ${LicLastName}
      Email: ${LicEmail}
      Company: ${LicCompany}
