apiVersion: v1
kind: Secret
metadata:
  name: login
type: Opaque
data:
  githubToken: "{{ .Values.OperationCenter.Credentials.Github.Token }}"
  githubUser: "{{ .Values.OperationCenter.Credentials.Github.User }}"
  jenkinsPass: "{{ .Values.OperationCenter.Security.JenkinsPass }}"
