jenkins:
  views:
    - masters:
        name: "Controllers"
        jobFilters:
          - "connectedMasterViewFilter"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "manageMaster"
          - "masterConfigurationStaleViewColumn"
          - "totalJobsViewColumn"
          - "queueSizeViewColumn"
          - "jenkinsVersionViewColumn"
          - "cascViewColumn"
          - "listSelectionColumn"
    - all:
        name: "all"
unclassified:
  cascAutoControllerProvisioning:
    provisionControllerOnCreation: true
    # Best-Practice: Discard Old Builds
    # https://support.cloudbees.com/hc/en-us/articles/215549798
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "3"
  usageStatisticsCloudBees:
    disabledJenkinsUsageStatistics: true
    usageStatisticsCollected: false
cloudBeesCasCServer:
  defaultBundle: "general"
  visibility: true
# Best-Practice: Enable Beekeeper
beekeeper:
  enabled: true
  securityWarnings:
    enabledForCore: true
    enabledForPlugins: true
  upgrades:
    autoDowngradePlugins: false
    autoUpgradePlugins: true
# Best-Practice: Operations at Scale. CloudBees Advisor
advisor:
  acceptToS: true
  email: "example.user@mail.com"
  excludedComponents:
    - "AgentsSystemConfiguration"
    - "KubernetesMasterLogs"
    - "AgentsJVMProcessSystemMetricsContents"
    - "GCLogs"
    - "AgentsConfigFile"
    - "ConfigFileComponent"
    - "RootCAs"
    - "SlaveLogs"
    - "OtherConfigFilesComponent"
    - "HeapUsageHistogram"
    - "OtherLogs"
    - "SlaveLaunchLogs"
  nagDisabled: false
  # Node pools for Kubernetes installation
  # masterprovisioning:
  #   kubernetes:
  #     yaml: |-
  #       kind: StatefulSet
  #       spec:
  #         template:
  #           metadata:
  #             annotations:
  #               cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  #           spec:
  #             tolerations:
  #               - key: "dedicated"
  #                 operator: "Equal"
  #                 value: "apps"
  #                 effect: "NoSchedule"
