apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-load-casc-bundle
  annotations:
    docs: "https://docs.cloudbees.com/docs/cloudbees-ci/latest/casc-controller/"
data:
  bundle.yaml: |
{{ .Files.Get "casc/controllers/modern.load-boy/bundle.yaml" | indent 4 }}
  jenkins.yaml: |
{{ .Files.Get "casc/controllers/modern.load-boy/general.yaml" | indent 4 }}
  plugins.yaml: |
{{ .Files.Get "casc/controllers/modern.load-boy/plugins.yaml" | indent 4 }}
  plugin-catalog.yaml: |
{{ .Files.Get "casc/controllers/modern.load-boy/plugin-catalog.yaml" | indent 4 }}
  items-load-jobs.yaml: |
    removeStrategy:
      items: NONE
      rbac: SYNC
{{- if gt (int .Values.LoadControllers.JobsPerController) 0 }}
    items:
{{- range (untilStep 0 (int .Values.LoadControllers.JobsPerController) 1) }}
    - kind: pipeline
      name: pipeline-scripted-load{{ . }}
      concurrentBuild: true
      properties:
        - pipelineTriggers:
            triggers:
              - cron:
                  spec: H/30 * * * *
      definition:
        cpsFlowDefinition:
          sandbox: true
          script: |
            parallel([0, 1].collectEntries {b -> ["branch-$b", {
              podTemplate {
                node("maven") {
                  stage('prep') {
                    sh 'curl https://ipinfo.io/'
                  }
                  stage('build') {
                    mockLoad 180
                  }
              }
              checkpoint 'middle'
              podTemplate {
                node("maven") {
                  stage('publish') {
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'mock-artifact-*.txt'
                    fingerprint 'mock-artifact-*.txt'
                    junit 'mock-junit.xml'
                  }
                }
              }
            }}]})
            build job: JOB_NAME, wait: false
{{- end }}
{{- else }}
    items: []
{{- end }}
  rbac.yaml: |-
{{ .Files.Get "casc/oc/modern/rbac.yaml" | indent 4 }}
