apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-casc-bundle
  annotations:
    docs: "https://docs.cloudbees.com/docs/cloudbees-ci/latest/casc-oc/configure-oc-modern"
data:
  bundle.yaml: |-
{{ .Files.Get "casc/oc/modern/bundle.yaml" | indent 4 }}
  main.yaml: |-
{{ .Files.Get "casc/oc/modern/main.yaml" | indent 4 }}
  location.yaml: |-
    unclassified:
      location:
{{- if eq .Values.OperationCenter.Ingress.Class "alb" }}
          url: {{ .Values.OperationCenter.Protocol }}://cjoc.{{ .Values.OperationCenter.Hostname }}
{{- else }}
          url: {{ .Values.OperationCenter.Protocol }}://{{ .Values.OperationCenter.Hostname }}/cjoc/
{{- end }}
  controllerBundleStorageSCM.yaml: |-
    unclassified:
      # Best-Practice: Use SCM for Managed Master Casc Bundles
      # https://docs.cloudbees.com/docs/cloudbees-ci/2.332.3.4/casc-controller/add-bundle#_adding_casc_bundles_from_an_scm_tool
      bundleStorageService:
        activated: true
        activeBundle:
          name: "casc-store"
          retriever:
            SCM:
              scmSource:
                git:
                  credentialsId: "GH-token"
                  remote: {{ .Values.OperationCenter.Casc.ControllerBundleStorageSCM }}
                  traits:
                    - "gitBranchDiscovery"
  credentials.yaml: |-
{{ .Files.Get "casc/oc/modern/credentials.yaml" | indent 4 }}
  security.yaml: |-
{{ .Files.Get "casc/oc/modern/security.yaml" | indent 4 }}
  plugins.yaml: |-
{{ .Files.Get "casc/oc/modern/plugins.yaml" | indent 4 }}
  items-controllers.yaml: |-
{{ .Files.Get "casc/oc/modern/items-controllers.yaml" | indent 4 }}
  items-load-controllers.yaml: |-
    removeStrategy:
      items: NONE
      rbac: SYNC
{{- if gt (int .Values.ManagedControllers.loadCount) 0 }}
    items:
{{- range (untilStep 0 (int .Values.ManagedControllers.loadCount) 1) }}
    - kind: managedController
      name: load-boy{{ . }}
      properties:
      - configurationAsCode:
          bundle: "modern.load-boy"
      configuration:
        kubernetes:
          domain: load-boy{{ . }}
          memory: 1500
          cpus: 1.0
          disk: 30
{{- end }}
{{- else }}
    items: []
{{- end }}
  rbac.yaml: |-
{{ .Files.Get "casc/oc/modern/rbac.yaml" | indent 4 }}
