#https://kubernetes.github.io/ingress-nginx/
#https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
#AWS - it will create an ELB Classic
controller:
  ingressClass: nginx
  nodeSelector:
    kubernetes.io/os: linux
  service:
    externalTrafficPolicy: Local
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux
defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
